<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>a94330bf-f7d4-43d6-988c-247d8cd38e77</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Escapade.Booking.Core\Escapade.Booking.Core.csproj" />
    </ItemGroup>

</Project>
