<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>a94330bf-f7d4-43d6-988c-247d8cd38e77</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Escapade.Booking.Core\Escapade.Booking.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Location\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Views\Shared\_Layout.nl.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.nl.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Shared\_Layout.fr.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.fr.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Shared\_Layout.en.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Home\Index.nl.resx">
        <LastGenOutput>Index.nl.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Home\Index.fr.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.fr.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Home\Index.en.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Views\Shared\_Layout.nl.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.nl.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Views\Shared\_Layout.fr.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.fr.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Views\Shared\_Layout.en.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.en.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
